type LabelColorsType =
  | 'labelRed'
  | 'labelPink'
  | 'labelOrange'
  | 'labelYellow'
  | 'labelGreen'
  | 'labelLeaf'
  | 'labelBlue'
  | 'labelSky'
  | 'labelNavy'
  | 'labelIndigo'
  | 'labelPurple'
  | 'labelLavender'
  | 'labelCharcoal'
  | 'labelBrown'
  | 'warmGray'
  | 'coolGray';
